.TH GIT\-COAUTHOR 1 2024-02-16 5.2.2 Git\ Manual
.SH NAME
\fBgit\-coauthor\fR \- List, add or delete Git coauthors
.SH SYNOPSIS
\fBgit coauthor\fR [-d] [\fIalias \.\.\.\fR]
.SH DESCRIPTION
Git coauthor manages "Co-authored-by" lines on the HEAD commit. Coauthors are specified as names from the repository's commit history or aliases configured via `git config`\.
.SH OPTIONS
.TP
\fB\-d, \-\-delete\fR
Delete coauthors\.
.TP
\fB\-h, \-\-help\fR
Print help\.
.TP
\fB\-v\, \-\-version\fR
Print the version\.
.SH CONFIGURATION
.PP
Optionally, coauthor aliases can be added to the Git config:
.PP
.RS 4
.nf
git config --add coauthor.joe 'Joe Blow <foo@foo.com>'
.fi
.RE
.PP
To remove a coauthor from the Git config:
.PP
.RS 4
.nf
git config --unset coauthor.joe
.fi
.RE
.SH EXAMPLES
List coauthors on the HEAD commit:
.PP
.RS 4
git coauthor
.RE
.PP
Add coauthors to the HEAD commit:
.PP
.RS 4
git coauthor Joe
git coauthor Joe Jim
git coauthor "Joe Blow" "Jim Bob"
.RE
.PP
Delete coauthors from the HEAD commit:
.PP
.RS 4
git coauthor -d Joe
git coauthor -d Joe Jim
git coauthor -d "Joe Blow" "Jim Bob"
.RE
.PP
Delete all coauthors from the HEAD commit:
.PP
.RS 4
git coauthor -d
.RE
