# See https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "git-coauthor"
version = "6.1.0"
edition = "2021"
authors = ["Nick Dower <nicholasdower@gmail.com>"]

[dependencies]
clap = { version = "4.5", features = ["derive"] }
git2 = "0.18"
