# See https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "git-coauthor"
version = "1.0.0"
edition = "2021"
authors = ["Nick Dower <nicholasdower@gmail.com>"]

[dependencies]
clap = { version = "4.0", features = ["derive"] }
home = "0.5"
serde_yaml = "0.9"
git2 = "0.18"
