name: Build Release

on:
  workflow_dispatch:
  push:
    branches:
      - mac-build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create
        run: echo foo > foo
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: foo
          path: foo
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download
      uses: actions/download-artifact@v4
      with:
        name: foo
    - name: Show
      run: cat foo
